name: GodsVsHeroes
main: by.dero.gvh.Plugin
authors: [Derovi, Hattonuri]
version: 0.6.8
api-version: 1.13
depend: [WorldEdit, FastAsyncWorldEdit]
commands:
  # Main plugin command
  game:
    aliases: [gvh]
