name: GodsVsHeroes
main: by.dero.gvh.Plugin
authors: [Derovi, Hattonuri]
version: 0.6.8
api-version: 1.12.2
depend: [CoreAPI]
commands:
  # Main plugin command
  game:
    aliases: [gvh]
  test:
  bug:
    aliases: [bugreport]
  advice:
  bookapi:
  ether:
  thx:
